packages:
- packages/onyx-lib
- packages/onyx-lib-game
- packages/onyx-exe-toolkit
- packages/onyx-ffmpeg
- packages/onyx-handle
extra-deps:
- conduit-audio-0.2.0.3
- conduit-audio-lame-0.1.2.1
- conduit-audio-samplerate-0.1.0.3
- conduit-audio-sndfile-0.1.2.2
- jammittools-0.5.5.2
- rubberband-0.1.0.2
- tinyfiledialogs-0.2.0.0
- JuicyPixels-stbir-0.1.0.0
- wavefront-0.7.1.4
- caerbannog-1.0.0.2
- RtMidi-0.5.0.2
- inline-c-0.9.1.10
- inline-c-cpp-0.5.0.2
# local folders
- packages/onyx-arktool
- packages/onyx-kakasi
- packages/onyx-gamecube-dsp
- packages/onyx-wwise
- packages/onyx-npdata
- packages/onyx-moggcrypt
- packages/onyx-autochart
# git repos
- git: https://github.com/mtolly/midi
  commit: 67c595a8f0c3b2fa193c088374de5bf544234ff0 # string-param branch
- git: https://github.com/mtolly/conduit-audio
  commit: 0a90a9541b261583a09e5d5f9f416bc7ae59d07d
  subdirs:
  - conduit-audio-mpg123
- git: https://github.com/mtolly/fltkhs
  # from TheGreatConsolidation upstream branch with several edits:
  # - updated fltk due to file picker bug in macos monterey
  #   as well as drag and drop bug in wayland
  # - fix some bindings on all platforms due to that update
  # - add some screen scale function bindings
  # - put built fltk and c-lib under onyx's .stack-work, instead of /tmp
  # - newer fltk also supports kdialog but I disabled that until it's more polished
  commit: 993a8edb42849c517c1ee86afdfd255ec4a2ba16
  subdirs:
  - fltkhs
- git: https://github.com/mtolly/midi-util
  commit: e58affa31251cec0d50f9b0588acfa514edd58ae # string-param branch
- git: https://github.com/mtolly/OpenAL
  commit: 3c74c9807c2d126cbbd2596082f9b9345a247ec5
- git: https://github.com/mtolly/codec # ghc 8.8+ (to 9.6) and aeson patches
  commit: a6b98bbc1e37a7835b6c59a4425aa57600cf386e
- git: https://github.com/mtolly/mpg123-haskell-binding
  commit: 4790b92549b7db51801a67cf1055259e3abcf60e
- git: https://github.com/mtolly/shake # disables shake controlling the thread count
  commit: a4ecb069cbce6d4566e2dd025bcc79b8f8a5839d
- git: https://github.com/mtolly/tcp-streams # ghc 9.6 patch
  commit: 0269618e5e73e11026b45bd9e59a677dc89b1c23
- git: https://github.com/mtolly/onyx-libzip
  commit: 3af4544b752ab552b16dd1ccdd6d4cd02def2988
- git: https://github.com/mtolly/utf8proc-hs
  commit: 5ed6b59099013be261764a8ac2ff158c0f3e0066
- git: https://github.com/mtolly/hsndfile # unreleased upstream past 0.8.0 (switches to pkg-config), also add opus to enum
  commit: e02e1d9236d2a0959d0c81ac55f48d61f0b14979
resolver: nightly-2023-08-29
flags:
  fltkhs:
    bundled: true
    opengl: true
allow-newer: true
