name: onyx-exe-toolkit
version: '20240418'
github: mtolly/onyx
author: Michael Tolly <miketolly@gmail.com>
category: Distribution
license: GPL-3
license-file: ../../LICENSE.txt

extra-source-files:
- ../../icon/icon.*

ghc-options: -Wall

executables:

  onyx:
    source-dirs: src
    main: Main.hs
    c-sources:
    - cbits/time_monotonic.c

    dependencies:
    - base
    - directory
    - aeson
    - text
    - bytestring
    - unordered-containers
    - filepath
    - yaml
    - process
    - resourcet
    - hsndfile
    - transformers
    - data-default-class
    - stm
    - req
    - fltkhs
    - midi
    - event-list
    - containers
    - time
    - non-negative
    - binary
    - random
    # - tcp-streams
    # - io-streams
    - fsnotify
    - gl
    - async
    - network
    - exceptions
    - extra
    - JuicyPixels
    - hashable
    # my libraries
    - midi-util
    - conduit-audio
    # local
    - onyx-lib
    - onyx-lib-game
    - onyx-handle

    ghc-options: -threaded -O -with-rtsopts=-N

    when:
    - condition: os(mingw32)
      then:
        cpp-options: -DWINDOWS
        ld-options: ../../icon/icon.o -mwindows
        dependencies: Win32
        cxx-sources:
        - cbits/win_open_folder.cpp
        cxx-options: -std=c++11
      else:
        dependencies: mountpoints
    - condition: os(darwin)
      cpp-options: -DMACOSX
      # copied from fltkhs-hello-world, also unwind is to avoid https://gitlab.haskell.org/ghc/ghc/issues/11829
      ghc-options: "-optl-Wl,-lfltkc -optl-Wl,-keep_dwarf_unwind"

  onyx-package:
    main: Installer.hs
    dependencies: [base, nsis, text, process, containers, filepath, directory, bytestring]

  onyx-cli:
    main: CLI.hs
    dependencies: [base, onyx-lib, resourcet]
